use customer_shoping;

# --Q1. What is the total revenue generated by male vs. female customers?

select 
	gender,
	sum(purchase_amount) as revenue
from final_customer
group by gender;

# --Q2. Which customers used a discount but still spent more or equal to the the average purchase amount?
select 
	customer_id,
	purchase_amount,
	discount_applied 
from final_customer
where discount_applied = 'Yes' and purchase_amount >= (select 
														avg(purchase_amount) as avg_purchase
													  from final_customer);

#--Q3. Which are the top 5 products with the highest average review rating?
select 
	item_purchased,
    round(avg(review_rating),2) as avg_review_rating
from final_customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

#--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select
	shipping_type,
    round(avg(purchase_amount),2) avg_purchase_amount
from final_customer
where shipping_type = 'Express'
group by shipping_type
union all
select
	shipping_type,
    round(avg(purchase_amount),2) avg_purchase_amount
from final_customer
where shipping_type = 'Standard'
group by shipping_type;

# or Diff solution
select
	shipping_type,
    round(avg(purchase_amount),2) avg_purchase_amount
from final_customer
where shipping_type in ( 'Express','Standard')
group by shipping_type;

#--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select
	subscription_status,
	count(customer_id),
	round(avg(purchase_amount),2),
    round(sum(purchase_amount),2)
from final_customer
where subscription_status = 'Yes'
union all
select
	subscription_status,
	count(customer_id),
	round(avg(purchase_amount),2),
    round(sum(purchase_amount),2)
from final_customer
where subscription_status = 'No';

# OR
select
	subscription_status,
	count(customer_id),
	round(avg(purchase_amount),2) avg_spend,
    round(sum(purchase_amount),2) total_revenue
from final_customer
group by subscription_status 
order by avg_spend , total_revenue desc;


#--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select
	item_purchased,
    round((sum(case
		when discount_applied = 'Yes' then 1 else 0 end ) /count(*))*100,2) as discount_rate
from final_customer
group by item_purchased
order by discount_rate desc
limit 5;

#--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
# and show the count of each segment.

With customer_segment as (select
	customer_id,
    previous_purchases,
	case
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loayl'
	end as cust_seg
from final_customer)
select 
	cust_seg,
	count(*) as no_of_count
from customer_segment
group by cust_seg
order by no_of_count desc;

#--08. What are the top 3 most purchased products within each category?

select
	category,
    item_purchased,
    c,
    rnk
from(select 
	category,
    item_purchased,
    count(customer_id) c,
    row_number() over(partition by category order by count(customer_id) desc) rnk
from final_customer
group by category,item_purchased)t
where rnk<=3;


#--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select
	subscription_status,
    count(customer_id)
from final_customer
where previous_purchases > 5 
group by subscription_status;

#--Q10. What is the revenue contribution of each age group?

select
	age_group,
    sum(purchase_amount) total_rev
from final_customer
group by age_group
order by total_rev desc;
